### ISSUE TITLE
RPP fails to handle free variable in predicate

### ISSUE THREAD

**Issue by LangInteger** [lyonel2017/Frama-C-RPP#1]
Hi, see the code snippet (which is similar to the `more_pointer.c` example) below:

```C
/*@ predicate equal{L1, L2}(int* x, int* y)
  = \at(*x, L1) == \at(*y, L2);
*/

/*@ requires \valid(x+(0..1));
  @ assigns *x \from *x;
*/
void f(int* x){
  *x = *x + 1;
}

/*@ relational
      \forall int *x1,*x2;
      \callset(\call(f,x1,id1),\call(f,x2,id2)) ==>
      equal{Post_id1,Pre_id2}(x1,x2);
*/
```

RPP can generate code with`frama-c -rpp -rpp-pro ./test.c` for this. But for the following code it fails with an error:

- no label in the context. (\at or explicit label missing?).

the code is:

```C
/*@ predicate equal{L1, L2}(int* x, int* y)
  = \at(*x, L1) == \at(*y, L2);
*/

int y = 1;
int* x = &y;

/*@ requires \valid(x+(0..1));
  @ assigns *x \from *x;
*/
void f(){
  *x = *x + 1;
}

/*@ relational
      \callset(\call(f,id1),\call(f,id2)) ==>
      equal{Post_id1,Post_id2}(x, x);
*/
```

@lyonel2017 hi, yonel. I am wondering why the second demo code cannot work with RPP. I would appreciate it if you could have a look at this at your earliest convenience!

**Comment by lyonel2017** [comment]
Hello, 
Passing relational state labels as parameters to a predicate is not currently supported by RPP.

Furthermore, passing `x` as a parameter to the `equal` predicate has an unclear meaning. `x` exists in both id1 and id2 calls of f.
A clearer specification would probably look like
```c
/*@ relational
      \callset(\call(f,id1),\call(f,id2)) ==>
      equal{Post_id1,Post_id2}(\at(x,Post_id1), \at(x,Post_id2));
*/
```
However, such a specification seems redundant, and is not supported by RPP.

**Comment by LangInteger** [comment]
Hi yonel, 

I will avoid using `predicate` with `RPP` in my code.
Thanks for you help!
